racker/salus-telemetry-etcd-adapter

- src/main/java/com/rackspace/salus/telemetry/etcd/services/EnvoyNodeManagement.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/EnvoyNodeManagementTest.java
Follows on from https://github.com/racker/salus-telemetry-model/pull/5
We cannot use abstract classes so must use `InetSocketAddress` instead.
The extra tests validate that we can deserialize and retrieve the correct values.
> Fix NodeInfo Serialization & Add better tests

- src/main/java/com/rackspace/salus/telemetry/etcd/services/EnvoyNodeManagement.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/EnvoyNodeManagementTest.java
Adds a method to remove nodes from etcd.
Removes both the expected and active keys.  If the active key wasn't removed it'd expire shortly afterwards, but we might as well try and remove everything at the same time to avoid confusing any troubleshooting.
Run the test.
This'll be needed as part of the identifier api.
> Add delete node methods

- src/main/java/com/rackspace/salus/telemetry/etcd/services/EnvoyNodeManagement.java
- src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/EnvoyNodeManagementTest.java
https://jira.rax.io/browse/SALUS-73
Creates a new key in redis containing connection status details.
I chose to create it at `/tenants/{tenant}/identifiers/{identifier}:{identifierValue}` rather than `identifiers/{tenantId}/{identifierKey}:{identiferValue}` like the wiki stated.
It is created with no lease.  I am assuming that these keys and the `expected` keys will be tightly coupled together.  Any cleanup performed should remove both of them.  That should only be required when devices go offline or when an identifier is changed for a device.
Uses the new model from https://github.com/racker/salus-telemetry-model/pull/4 as the value stored.
Run the `testRegister` test or run an ambassador and connect a new envoy.  You will see this get created in etcd:
``` …
```
> Create identifier keys when envoys connect

- src/main/java/com/rackspace/salus/telemetry/etcd/lombok.config
- src/main/java/com/rackspace/salus/telemetry/etcd/services/AgentsCatalogService.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/ConfigService.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/EnvoyLabelManagement.java
- src/main/java/com/rackspace/salus/telemetry/etcd/types/AgentInstallSelector.java
- src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/AgentsCatalogServiceTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/ConfigServiceTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/EnvoyLabelManagementTest.java
Part of SALUS-81
While converting the public REST API to GraphQL I noticed there were some missing operations since I had skipped them for the POC development.
Also needed to accomodate model rename from https://github.com/racker/salus-telemetry-model/pull/6
Standard unit tests
n/a
In a separate PR I will be making changes for the work partitioning API.
> Adding a couple more agent config and release operations for public api

- src/main/java/com/rackspace/salus/telemetry/etcd/TelemetryCoreEtcdModule.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/EnvoyResourceManagement.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/WorkAllocationPartitionService.java
- src/main/java/com/rackspace/salus/telemetry/etcd/types/EnvoySummary.java
- src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/WorkAllocationPartitionServiceTest.java
- src/test/resources/application.yml
part of https://jira.rax.io/browse/SALUS-77
adds a couple of utility functions for the presence monitor
presence monitor tests
this is to be merge to the rebased branch of the partitions api:
https://github.com/racker/salus-telemetry-etcd-adapter/pull/10
> Add utility functions for presence monitor

- pom.xml
I think these are now required due to the shuffling around of models / protocol repos.
> Add lombok and validation to pom

- pom.xml
- src/test/java/com/rackspace/salus/telemetry/etcd/services/AgentsCatalogServiceTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/ConfigServiceTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/EnvoyLabelManagementTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/EnvoyLeaseTrackingTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/EnvoyResourceManagementTest.java
SALUS-145
Upgrade dependency management from Spring Boot to 2.1.2. 2.1.x is stricter about the unit test app context annotations and could no longer mix the `@JsonTest` with the `@SpringBootTest`, which actually makes sense.
Via dependent application unit tests
> Upgrade to Spring Boot 2.1.2

- pom.xml
- src/main/java/com/rackspace/salus/telemetry/etcd/TelemetryCoreEtcdModule.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/EtcdHealthIndicator.java
Helps SALUS-93
Adds an etcd health indicator so that k8s pod health checks using the {{/actuator/health}} endpoint will also be confirming etcd connectivity.
I tested manually by bringing up the ambassador app with the etcd container already running. Then I stopped etcd and hit the health endpoint again. Lastly, I started the container again and confirmed health went back to UP.
```
➜  ~ curl localhost:8081/actuator/health
{"status":"UP"}%                                                                                                                                      ➜  ~ curl localhost:8081/actuator/health
{"status":"UP","details":{"etcd":{"status":"UP"},"diskSpace":{"status":"UP","details":{"total":250140434432,"free":35397124096,"threshold":10485760}}}}% …
```
> Adding etcd health indicator to assist k8s deployment health

- src/test/java/com/rackspace/salus/telemetry/etcd/services/AgentsCatalogServiceTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/ConfigServiceTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/EnvoyLabelManagementTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/EnvoyLeaseTrackingTest.java
Unit tests were failing to load the etcd health indicator. Introducing that might have been when the tests broke. Apparently `@JsonTest` doesn't disable component scanning as I expected, so those unit tests were still loading all the service and config beans, but those aren't needed for the unit tests.
Use the Spring testing strategy of including an inner configuration class to override the app context declaration.
> Narrow the app context in unit tests using @JsonTest

- src/main/java/com/rackspace/salus/telemetry/etcd/services/EnvoyResourceManagement.java
the getOne() method uses this key fmt:
https://github.com/racker/salus-telemetry-etcd-adapter/blob/ca0c69cf9100a1bc40666c20517b1156fea050e0/src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java#L45
That key fmt has been updated to use the resourceId, but the method still invokes it with the idName/value.  This PR addresses that problem.
> update getOne() method to use resourceId, instead of idName/value

- cloudbuild.yaml
- src/main/java/com/rackspace/salus/telemetry/etcd/EtcdUtils.java
- src/main/java/com/rackspace/salus/telemetry/etcd/TelemetryCoreEtcdModule.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/EnvoyResourceManagement.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorage.java
- src/main/java/com/rackspace/salus/telemetry/etcd/types/EtcdStorageException.java
- src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java
- src/main/java/com/rackspace/salus/telemetry/etcd/types/ResolvedZone.java
- src/test/java/com/rackspace/salus/telemetry/etcd/EtcdUtilsTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/WorkAllocationPartitionServiceTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorageTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/types/ResolvedZoneTest.java
Part of
- https://jira.rax.io/browse/SALUS-292
- https://jira.rax.io/browse/SALUS-305
Mainly introduces `ZoneStorage`, which is kind of a like a repository in JPA. It, along with the new `ResolveZone` model-utility-class, coordinate tracking envoys and resources in zones and the querying of zones to find the least loaded envoy. FYI, there will likely be more refinements and changes in this area as we progress through more of remote polling scenarios.
Unit tests have been added and extended
> Support remote polling with zone storage

- src/test/java/com/rackspace/salus/telemetry/etcd/EtcdUtilsTest.java
Fixes an issue reported later in https://github.com/racker/salus-telemetry-etcd-adapter/pull/27
Removes some unit test argument matchers I originally needed for an alternate use of etcd for registering envoys in zones.
Existing unit tests
> Remove unused test argument matchers for ByteSequences

- src/main/java/com/rackspace/salus/telemetry/etcd/EtcdUtils.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/EnvoyResourceManagement.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorage.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorageListener.java
- src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java
- src/main/java/com/rackspace/salus/telemetry/etcd/types/ResolvedZone.java
- src/test/java/com/rackspace/salus/telemetry/etcd/EtcdUtilsTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/EnvoyResourceManagementTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorageTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/types/ResolvedZoneTest.java
Part of https://jira.rax.io/browse/SALUS-263
These changes encapsulate the etcd specific parts of watching the expected zone keys and then the new zone management code (soon to be PR'ed) will use these to kick off and listen for zone related changes.
Unit tests have been added.
> Add support for zone watching in ZoneStorage

- src/main/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorage.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorageTest.java
Adds a method to get the number of active envoys for a zone.
Before deleting a zone we do checks to see that it has no envoys connected and fail if it does.
> Add ability to get number of active envoys in zone

- src/main/java/com/rackspace/salus/telemetry/etcd/types/ResolvedZone.java
- src/test/java/com/rackspace/salus/telemetry/etcd/types/ResolvedZoneTest.java
With the changes in https://github.com/racker/salus-telemetry-monitor-management/pull/29 we have solidified the field for a zone's name, such as "public/west", vs its `id` which is actually an internal database ID.
Refer to `name` rather than `id` to emphasize the relationship to `Zone`'s fields.
Unit test updated
> Renaming id of ResolveZone to name to align with zone management

- src/main/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorage.java
- src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java
Creates a distinct key to use for tracking expected zone revisions.
Hoping existing tests are good enough.
Using the `PREFIX_ZONE_EXPECTED` for multiple purposes confused things a little and made it seem like there was more of a relationship between the "tracking" key and the keys that were written whenever a new zone was registered.
I'm hoping my added documentation is correct, particularly the last section of Keys.java.  Kinda wishing I had done this after we chatted about all of this.
> Change expected zones tracking key

- src/test/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorageTest.java
This needs to change due to https://github.com/racker/salus-telemetry-etcd-adapter/pull/34
> Fix tracking key in test

- .github/PULL_REQUEST_TEMPLATE.md
- src/main/java/com/rackspace/salus/telemetry/etcd/services/AgentsCatalogService.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/AgentsCatalogServiceTest.java
https://jira.rax.io/browse/SALUS-370
When using the public API to perform an agent installation, it would fail with a 500 and NullPointerException when the given `agentReleaseId` didn't exist.
Throw a `NotFoundException` which eventually gets picked up by the Spring MVC layer when consuming the completable future.
Unit test added
> Improve handling of missing agent release during install

- src/main/java/com/rackspace/salus/telemetry/etcd/services/ZoneNameValidators.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorage.java
- src/main/java/com/rackspace/salus/telemetry/etcd/types/PrivateZoneName.java
- src/main/java/com/rackspace/salus/telemetry/etcd/types/PublicZoneName.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/ZoneNameValidatorsTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorageTest.java
Part of https://jira.rax.io/browse/SALUS-294
The rebalancing code in monitor management needed the ability to query for the per-envoy-resource assignment accounts within a given zone.
It also needs to do a "bulk decrement" of the active envoy-resource assignments, so I generalized the existing method by renaming it and fixing the log messages.
Unit tests have been added
> Support zone rebalancing with getZoneBindingCounts

- src/main/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorage.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorageTest.java
This is needed by https://github.com/racker/salus-telemetry-monitor-management/pull/51
It returns a mapping of envoy id -> resource id for a given zone.
> Add envoy id to resource id helper

- pom.xml
- src/main/java/com/rackspace/salus/telemetry/etcd/EtcdUtils.java
- src/main/java/com/rackspace/salus/telemetry/etcd/TelemetryCoreEtcdModule.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/EnvoyLeaseTracking.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/EnvoyResourceManagement.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/EtcdHealthIndicator.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/WorkAllocationPartitionService.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorage.java
- src/main/java/com/rackspace/salus/telemetry/etcd/types/KeyedValue.java
- src/test/java/com/rackspace/salus/telemetry/etcd/EtcdUtilsTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/EnvoyLeaseTrackingTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/EnvoyResourceManagementTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/WorkAllocationPartitionServiceTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorageTest.java
https://jira.rax.io/browse/SALUS-474
This is one of our two libraries that uses the jetcd library. Since they are still 0.x they took some liberties with the API switch from 0.0.2 to 0.3.0. (Already notice the change in semantic version position there.)
- Use the new `io.etcd` group for dependencies. They now maintain the unit testing `jetcd-launcher`.
- Switch package references to `io.etcd.jetcd`
- The API leverages more of the asynchronous features of the etcd protocol, such as with the watcher. No longer need to do our own blocking `listen` call
- The string conversion calls don't make their own character set assumptions
- Some of the "data" types are now "top level" types in `io.etcd.jetcd`
Existing unit tests
> Upgraded to jetcd 0.3.0

- src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java
All these keys are currently unused.
Looking at this makes me wonder why `FMT_IDENTIFIERS` is still used, but I wasn't going to spend the time at the moment to see if it can be cleaned up too.
> Remove unused etcd keys

- pom.xml
- src/main/java/com/rackspace/salus/telemetry/etcd/EtcdProperties.java
- src/main/java/com/rackspace/salus/telemetry/etcd/TelemetryCoreEtcdModule.java
https://jira.rax.io/browse/SALUS-582
Now that etcd is running in a cluster separate from the apps and Istio doesn't manage external connectivity, we need to allow for https configuration of the etcd clients.
Since the jetcd docs lacked details, extrapolated the solution from the gRPC Java docs here
https://grpc.io/docs/guides/auth/#java
and here
https://github.com/grpc/grpc-java/blob/master/SECURITY.md#tls-with-netty-tcnative-on-boringssl
to see how to pass a CA cert file to the jetcd client builder.
The environment variable binding for the new property is `SALUS_ETCD_CACERT`.
Will have to test on dev cluster.
> Add an option to pass CA cert to etcd client configuration

- src/main/java/com/rackspace/salus/telemetry/etcd/services/EnvoyLeaseTracking.java
- src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/EnvoyLeaseTrackingTest.java
Prep for https://jira.rax.io/browse/SALUS-586
In preparation for the issue above, I wanted to research where we still track envoys in etcd. This was the only potential key for that and turned out the only usage was in a unit test.
Removed the dead code and unused key to avoid confusion.
Existing tests
> Removing etcd key "envoysById" since it's not actually used

- pom.xml
Part of https://jira.rax.io/browse/SALUS-738
Bumped Spring Boot version to 2.2.4. No other changes (like the h2->mysql DB stuff) were needed in this module.
The jacoco upgrade was luckily an easy fix for a bizarre looking error I saw when running `mvn test`:
```
[DEBUG] Forking command line: /bin/sh -c cd /Users/geof0549/git/salus-telemetry-bundle/libs/etcd-adapter && /Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home/bin/java -javaagent:/Users/geof0549/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/Users/geof0549/git/salus-telemetry-bundle/libs/etcd-adapter/target/jacoco.exec org.apache.maven.surefire.booter.ForkedBooter /Users/geof0549/git/salus-telemetry-bundle/libs/etcd-adapter/target/surefire 2020-01-27T09-24-52_013-jvmRun1 …
```
> Bumped Spring Boot version to 2.2.4 and jacoco to 0.8.5

- pom.xml
Upcoming changes to salus-telemetry-model  will remove it's dependency on salus-common so we need to specifically include it in all services when needed.
> Add salus-common dependency

- src/main/java/com/rackspace/salus/telemetry/etcd/EtcdUtils.java
- src/main/java/com/rackspace/salus/telemetry/etcd/types/ResolvedZone.java
- src/test/java/com/rackspace/salus/telemetry/etcd/EtcdUtilsTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorageTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/types/ResolvedZoneTest.java
I am opening this now so that people can comment some of their thoughts while I work on the zone-watcher tests. 
https://jira.rax.io/browse/SALUS-694
The goal is to make the interaction with etcd case insensitive. Since etcd stores everything in a binary format and doesn't give any collation options there isn't a way to relax the etcd constraints on strings. It is case sensitive, period. The only way to get around this is to make all of our interactions with etcd either upper or lower case. 
While building the key we toLowerCase the result to make sure that anytime anyone uses the buildKey utility function it always comes out the correct case.
Run the unit tests
I had considered making everyones resourceId's the same case when we received them from the client but it is kind of bad to …
> toLowerCase EtcdUtils.buildKey

- src/main/java/com/rackspace/salus/telemetry/etcd/EtcdProperties.java
- src/main/java/com/rackspace/salus/telemetry/etcd/TelemetryCoreEtcdModule.java
https://jira.rax.io/browse/SALUS-873
When using Envoy's stress-connections with 600 connections over 1 minute on local laptop, there were observed connection stability issues and the JDK Flight Recorder data included 321 observed threads, 213 of which had the prefix "grpc-default-executor".
By setting a breakpoint on the top-level class involved in one of those threads I determined it was the jetcd client invocations that were allocating from a default thread pool executor. Being a default, there was no bound on the thread pool size.
This change instead uses a thread pool with one warm thread and a bounded number of threads. It also uses a SychronousQueue to put back pressure on callers, which works out fine since the callers are most often the Ambassador gRPC threads which are subject to …
> Added limit on etcd client executor thread pool

- src/main/java/com/rackspace/salus/telemetry/etcd/EtcdProperties.java
- src/main/java/com/rackspace/salus/telemetry/etcd/TelemetryCoreEtcdModule.java
In https://github.com/racker/salus-telemetry-etcd-adapter/pull/55 I misunderstood the behavior of the `SynchronousQueue` when the thread pool was at its limit. I thought it would use [the blocking put method](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/SynchronousQueue.html#put(E)), but instead it uses [the non-blocking offer method](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/SynchronousQueue.html#offer(E)).
As a result, when there were more than four concurrent etcd operations, the 5th would throw an exception:
```
2020-04-15 09:32:02.843 ERROR 2292 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
java.util.concurrent.RejectedExecutionException: …
```
> Fixed back pressure behavior of executor for etcd client calls

- src/main/java/com/rackspace/salus/telemetry/etcd/EtcdProperties.java
- src/main/java/com/rackspace/salus/telemetry/etcd/TelemetryCoreEtcdModule.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/EnvoyLeaseTracking.java
For https://jira.rax.io/browse/SALUS-852
I still couldn't decide what rejected execution policy will work best for us...
...so made it a configurable property with the default being the blocking-with-timeout mode. In the process I cleaned up the config class to have a factory method each for the executor and rejection policy.
With Ambassador and at least one Envoy connection, confirm that ready instruction is sent to Envoy.
> Added configuration for etcd rejected execution policy

- src/main/java/com/rackspace/salus/telemetry/etcd/EtcdProperties.java
- src/main/java/com/rackspace/salus/telemetry/etcd/TelemetryCoreEtcdModule.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/EnvoyLeaseTracking.java
With all the fancy thread executor setup and rejection policies in https://github.com/racker/salus-telemetry-etcd-adapter/pull/56 and https://github.com/racker/salus-telemetry-etcd-adapter/pull/58 it turned out that more than 4 concurrent etcd operations could get the Ambassador into a deadlocked state due to the CompletableFuture/chained call approach used extensively there. I didn't arrive at hard evidence of the deadlock, but I was able to consistently produce a "stuck" etcd thread executor when starting the envoy stress mode with 5 envoys all starting concurrently.
Went back to basics and created a fixed thread pool which also includes a job queue when the pool (of 4 threads by default) is full.
Tested locally with up to 10 current Envoy connections and then in perf cluster with 2000 …
> Switched to a simple fixed thread pool executor with queuing

- pom.xml
- src/main/java/com/rackspace/salus/telemetry/etcd/EtcdUtils.java
- src/main/java/com/rackspace/salus/telemetry/etcd/workpart/WorkAllocator.java
- src/test/java/com/rackspace/salus/telemetry/etcd/EtcdClusterResource.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/EnvoyResourceManagementTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorageTest.java
- src/test/java/com/rackspace/salus/telemetry/etcd/workpart/WorkAllocatorTest.java
Part of https://jira.rax.io/browse/SALUS-852
There was an issue where grpc server callbacks in ambassador were interfering with grpc client calls to etcd.
Upgraded jetcd to 0.5.3 which itself brings us to grpc 1.28.1, which is much closer to the latest version.
A lot of methods in `EtcdUtils` would have needed to be tweaked due to jetcd introducing a namespace option; however, I noticed a lot of methods were no longer used so I simply removed them.
Similar to the spring-boot pom import technique for declaring managed dependencies, I did the same with jetcd-parent so that it simplifies the individual dependency declarations and guarantees they're aligned.
jetcd [has dropped support for junit 4](https://github.com/etcd-io/jetcd/issues/742#issuecomment-619726628), so …
> Upgraded jetcd to 0.5.3 to upgrade grpc to 1.28.1

- src/main/java/com/rackspace/salus/telemetry/etcd/services/EtcdHealthIndicator.java
In the staging cluster the presence monitor was failing readiness/liveness probes and only failure indication in logs was:
```
2020-07-20 19:48:41.693 DEBUG 1 --- [nio-7777-exec-8] o.s.web.servlet.DispatcherServlet        : Failed to complete request: org.apache.coyote.CloseNowException: Failed write
```
When attaching with a debugger and setting a breakpoint in `EtcdHealthIndicator.health` the `Health.down(e).build()` line was hit and the caught exception was simply `java.lang.InterruptedException`.
Application logs otherwise indicate successful interaction with etcd.
Since I vaguely remember that health indicator causing weird issues before, I tagged it with a `@Profile` so that it would be excluded by default, but leaves the option to activate it later. I also added a debug log in the …
> Disabled etcd health indicator by default since it seems to cause false-negatives

- src/main/java/com/rackspace/salus/telemetry/etcd/TelemetryCoreEtcdModule.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/EtcdHealthIndicator.java
I had made a mistake in https://github.com/racker/salus-telemetry-etcd-adapter/pull/61 with the `@Profile` declaration since I didn't realize the health indicator was declared via an `@Bean`.
Moved the declaration to the `@Bean` itself.
Tested (again) locally by running the app, accessing the `/actuator/health` endpoint and confirm the etcd indicator wasn't involved.
> Shifted profile activation of EtcdHealthIndicator to bean declaration

- src/main/java/com/rackspace/salus/telemetry/etcd/workpart/Bits.java
- src/main/java/com/rackspace/salus/telemetry/etcd/workpart/WorkAllocator.java
- src/test/java/com/rackspace/salus/telemetry/etcd/workpart/WorkAllocatorTest.java
https://jira.rax.io/browse/SALUS-966
In staging we were observing that the partitions retrieval API call would time-out and before that the etcd health indicator check was failing with an `InterruptedException`. In the process of grabbing Java Flight Recorder data I thought I would simply get a stack dump after one of those API calls timed out. It turned out all of the etcd client threads were deadlocked on the `workChangeSem` semaphore which was used to (overly) protect access to a work load value:
https://gist.github.com/itzg/db621f21be7af68ca6d716e72dd79f97#file-gistfile1-txt
The `workLoad` aspect was always very brittle and led to the need for all the various unit tests. Simply removing the semaphore usage wasn't feasible since the brittle aspects of the algorithm were re-exposed with …
> Simplified the work-grabbing algorithm to avoid semaphore deadlock

- src/main/java/com/rackspace/salus/telemetry/etcd/TelemetryCoreEtcdModule.java
https://jira.rax.io/browse/SALUS-966
Even with the deadlock removed in [the previous PR](https://github.com/racker/salus-telemetry-etcd-adapter/pull/63), the etcd client calls still hit a deadlock at the point shown below. It's because 
1. the etcd thread pool was configured to limit to 8 threads
2. 8 partitions in etcd caused the event handler code in work allocator to occupy those 8 threads
3. within `PresenceMonitorProcessor.start` several more etcd calls are made, which need to make use of the thread pool
4. no threads are available, yet at the deadlocked line (176), there is a `join()` blocking on the etcd call
```java
at java.util.concurrent.locks.LockSupport.park(java.base@11.0.6/LockSupport.java:194)
at java.util.concurrent.CompletableFuture$Signaller.block(java.base@11.0.6/Complet …
```
> Switched etcd client to use cached thread pool

- src/main/java/com/rackspace/salus/telemetry/etcd/EtcdProperties.java
- src/main/java/com/rackspace/salus/telemetry/etcd/TelemetryCoreEtcdModule.java
- src/main/java/com/rackspace/salus/telemetry/etcd/services/EnvoyLeaseTracking.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/EnvoyLeaseTrackingTest.java
https://jira.rax.io/browse/SALUS-991
A recent attempt to fix a thread-pool-deadlock issue in https://github.com/racker/salus-telemetry-etcd-adapter/pull/64 worked well for presence-monitor; however, ambassador's handling of a large number of concurrent envoy attachments degraded since the JVM process would get overwhelmed with an unbounded number of threads being created.
Basically reverts https://github.com/racker/salus-telemetry-etcd-adapter/pull/64 but does things a bit better and cleaner:
- Use Spring's `ThreadPoolTaskExecutor` as a cleaner way to create a customizable thread pool executor
- Focus on core pool size, which is intuitively the parameter that primarily drives the number of threads to use
- ...but use `setAllowCoreThreadTimeOut` so that the number of core threads can scale …
> Restored etcd thread pool with limited core size, but with queuing

- src/main/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorage.java
- src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java
- src/main/java/com/rackspace/salus/telemetry/etcd/types/ResolvedZone.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorageTest.java
https://jira.rax.io/browse/SALUS-358
Rather than use a brittle, DIY counter in etcd, we'll instead use etcd to simply retrieve a list of the active poller's per remote monitoring zone and use the `BoundMonitor` table as the single source of truth for bindings per envoy-poller.
The motivation to make this change was observing my local system having troubles binding a new monitor to the 1000 resources I had left over from envoy-ambassador stress testing. The `ZoneStorage` code was getting itself into a tight loop of operations like the following with numerous collisions trying to increment the binding count:
```
2020-08-28 13:22:10.821 DEBUG [salus-telemetry-monitor-management,,,] 78771 --- [         etcd22] c.r.s.t.etcd.services.ZoneStorage        : Putting new bound count=894 for …
```
> Removing zone binding counts from etcd and using BoundMonitor table instead

- pom.xml
Tests fail after a Docker for Desktop update.
Fix them by upgrading to 1.15.0-rc2 to pick up testcontainers/testcontainers-java#3159
> Fix tests by using latest testcontainers

- src/main/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorage.java
- src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java
- src/test/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorageTest.java
https://jira.rax.io/browse/SALUS-992
Added method to support detached but pending timeout pollers
Created a method in ZoneStorage to get pollers which are detached but pending timeout.
This can be tested via unit test cases.
> Added method to support detached but pending timeout pollers
